
import { Parser } from '@json2csv/plainjs';
import PDFDocument from 'pdfkit';
import { calculateLineTotal, calculateQuoteTotals } from '../utils/quoteCalculations.js';
import { sanitizeCsvRows } from '../utils/csvSafe.js';

const money = (n) => `$${(n || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

// Human-readable column labels for the generic report exports below, e.g.
// 'weightedForecast' -> 'Weighted Forecast'. Opportunity export fields keep
// their own explicit header lists (see exportToPDF) since those are
// Salesforce field names, not camelCase report keys.
const humanizeField = (field) =>
  field
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/^./, (c) => c.toUpperCase());

class ExportService {
  async exportToCSV(opportunities) {
    return this.exportRowsToCSV(opportunities, [
      'Name',
      'Amount',
      'StageName',
      'CloseDate',
      'Probability',
      'AccountId',
    ]);
  }

  /**
   * Generic CSV export for any flat list of objects - backs the opportunity
   * export above as well as the dashboard stats and analytics report exports.
   */
  async exportRowsToCSV(rows, fields) {
    try {
      const parser = new Parser({ fields });
      return parser.parse(sanitizeCsvRows(rows));
    } catch (error) {
      throw new Error(`CSV export failed: ${error.message}`);
    }
  }

  async exportToPDF(opportunities, user) {
    const totalValue = opportunities.reduce((sum, opp) => sum + (opp.Amount || 0), 0);

    return this.exportReportToPDF({
      title: 'Sales Pipeline Report',
      user,
      summaryLines: [
        `Total Opportunities: ${opportunities.length}`,
        `Total Pipeline Value: $${totalValue.toLocaleString()}`,
      ],
      table: {
        headers: ['Opportunity Name', 'Amount', 'Stage', 'Close Date'],
        rows: opportunities.map((opp) => [
          opp.Name,
          `$${(opp.Amount || 0).toLocaleString()}`,
          opp.StageName,
          opp.CloseDate ? new Date(opp.CloseDate).toLocaleDateString() : '',
        ]),
      },
    });
  }

  /**
   * Generic PDF report builder - a title/generated-by header, optional
   * summary lines, and an optional table. Backs every PDF export in this
   * service (opportunities, dashboard stats, analytics reports).
   */
  async exportReportToPDF({ title, user, summaryLines = [], table = null }) {
    try {
      const doc = new PDFDocument({
        margin: 50,
        bufferPages: true,
      });

      doc.fontSize(20).text(title, { align: 'center' });
      doc.fontSize(12).text(`Generated by: ${user.name}`, { align: 'center' });
      doc.fontSize(10).text(`Date: ${new Date().toLocaleDateString()}`, {
        align: 'center',
      });
      doc.moveDown();

      if (summaryLines.length > 0) {
        doc.fontSize(12).text('Summary');
        doc.fontSize(10);
        summaryLines.forEach((line) => doc.text(line));
        doc.moveDown();
      }

      if (table) {
        this.addTable(doc, table);
      }

      return doc;
    } catch (error) {
      throw new Error(`PDF export failed: ${error.message}`);
    }
  }

  /**
   * Flatten the current Dashboard stats (see data.controller.js) into rows
   * suitable for exportRowsToCSV/exportReportToPDF - one row per pipeline
   * stage plus a TOTAL row carrying the overall summary.
   */
  buildDashboardStatsRows(stats) {
    return [
      ...(stats.stageBreakdown || []).map((s) => ({
        stage: s.stage,
        count: s.count,
        totalAmount: s.totalAmount,
        avgProbability: Math.round(s.avgProbability || 0),
        percentOfPipeline: s.percentOfPipeline,
      })),
      {
        stage: 'TOTAL',
        count: stats.totalOpportunities,
        totalAmount: stats.totalPipelineValue,
        avgProbability: stats.averageProbability,
        percentOfPipeline: 100,
      },
    ];
  }

  async exportDashboardStatsToCSV(stats) {
    return this.exportRowsToCSV(
      this.buildDashboardStatsRows(stats),
      ['stage', 'count', 'totalAmount', 'avgProbability', 'percentOfPipeline']
    );
  }

  async exportDashboardStatsToPDF(stats, user) {
    const rows = this.buildDashboardStatsRows(stats);

    return this.exportReportToPDF({
      title: 'Dashboard Stats Report',
      user,
      summaryLines: [
        `Total Opportunities: ${stats.totalOpportunities}`,
        `Total Pipeline Value: $${(stats.totalPipelineValue || 0).toLocaleString()}`,
        `Average Probability: ${stats.averageProbability}%`,
      ],
      table: {
        headers: ['Stage', 'Count', 'Total Amount', 'Avg Probability', '% of Pipeline'],
        rows: rows.map((r) => [
          r.stage,
          r.count,
          `$${(r.totalAmount || 0).toLocaleString()}`,
          `${r.avgProbability}%`,
          `${r.percentOfPipeline}%`,
        ]),
      },
    });
  }

  /**
   * Normalize one of the five AnalyticsService report shapes into a flat
   * {title, fields, rows, summaryLines} shape that exportAnalyticsToCSV/PDF
   * can render generically, instead of one bespoke exporter per report.
   */
  normalizeAnalyticsReport(reportType, data) {
    switch (reportType) {
      case 'health': {
        const rows = Object.entries(data.stageDistribution || {}).map(([stage, count]) => ({
          stage,
          count,
        }));
        return {
          title: 'Pipeline Health Report',
          fields: ['stage', 'count'],
          rows,
          summaryLines: [
            `Win Rate: ${data.winRate}%`,
            `Total Pipeline Value: $${(data.totalPipelineValue || 0).toLocaleString()}`,
            `Average Deal Size: $${Math.round(data.avgDealSize || 0).toLocaleString()}`,
            `Closed Won: ${data.closedWonCount} of ${data.totalOpportunities}`,
          ],
        };
      }

      case 'forecast': {
        const rows = Object.entries(data.byStage || {}).map(([stage, s]) => ({
          stage,
          count: s.count,
          totalValue: s.totalValue,
          weightedForecast: Math.round(s.weightedForecast || 0),
          avgDealSize: Math.round(s.avgDealSize || 0),
        }));
        return {
          title: 'Revenue Forecast Report',
          fields: ['stage', 'count', 'totalValue', 'weightedForecast', 'avgDealSize'],
          rows,
          summaryLines: [`Total Weighted Forecast: $${(data.totalForecast || 0).toLocaleString()}`],
        };
      }

      case 'risks': {
        const rows = (data || []).map((r) => ({
          opportunityName: r.opportunityName,
          riskScore: r.riskScore,
          riskLevel: r.riskLevel,
          daysToClose: r.daysToClose ?? '',
          risks: (r.risks || []).join('; '),
        }));
        return {
          title: 'Deal Risk Assessment',
          fields: ['opportunityName', 'riskScore', 'riskLevel', 'daysToClose', 'risks'],
          rows,
          summaryLines: [`Total Deals Assessed: ${rows.length}`],
        };
      }

      case 'team-performance': {
        const rows = Object.values(data || {}).map((s) => ({
          ownerName: s.ownerName,
          totalDeals: s.totalDeals,
          totalValue: s.totalValue,
          winRate: s.winRate,
          avgDealSize: Math.round(s.avgDealSize || 0),
          closedWon: s.closedWon,
        }));
        return {
          title: 'Team Performance Report',
          fields: ['ownerName', 'totalDeals', 'totalValue', 'winRate', 'avgDealSize', 'closedWon'],
          rows,
          summaryLines: [`Reps: ${rows.length}`],
        };
      }

      case 'revenue-trend': {
        const rows = Object.values(data || {}).map((m) => ({
          month: m.month,
          revenue: m.revenue,
          dealsCount: m.dealsCount,
          avgDealSize: Math.round(m.avgDealSize || 0),
        }));
        return {
          title: 'Revenue Trend Report',
          fields: ['month', 'revenue', 'dealsCount', 'avgDealSize'],
          rows,
          summaryLines: [],
        };
      }

      default: {
        const err = new Error(`Unknown analytics report type: ${reportType}`);
        err.status = 400;
        throw err;
      }
    }
  }

  async exportAnalyticsToCSV(reportType, data) {
    const { fields, rows } = this.normalizeAnalyticsReport(reportType, data);
    return this.exportRowsToCSV(rows, fields);
  }

  async exportAnalyticsToPDF(reportType, data, user) {
    const { title, fields, rows, summaryLines } = this.normalizeAnalyticsReport(reportType, data);

    return this.exportReportToPDF({
      title,
      user,
      summaryLines,
      table: {
        headers: fields.map(humanizeField),
        rows: rows.map((row) => fields.map((field) => row[field])),
      },
    });
  }

  /**
   * Render a Quote + its line items as a client-ready, styled PDF - the
   * server-side counterpart to the quote builder's live in-browser total
   * preview (quotesController.js's PDF/email endpoints call this). Uses the
   * exact same math as the frontend preview (see utils/quoteCalculations.js)
   * so nothing here can disagree with what the user saw while editing.
   */
  async exportQuoteToPDF(quote, lineItems, user) {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true });

      const totals = calculateQuoteTotals({
        lineItems: lineItems.map((li) => ({
          quantity: li.Quantity,
          unitPrice: li.UnitPrice,
          discount: li.Discount,
        })),
        discount: quote.Discount,
        tax: quote.Tax,
        shippingHandling: quote.ShippingHandling,
      });

      // Header
      doc.fontSize(20).font('Helvetica-Bold').fillColor('#111827').text('Sales Pipeline Intelligence', { align: 'left' });
      doc.fontSize(10).font('Helvetica').fillColor('#6b7280').text('Quotation & Proposal', { align: 'left' });
      doc.moveDown(1);

      doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text(quote.Name || 'Untitled Quote');
      doc.fontSize(10).font('Helvetica').fillColor('#6b7280').text(`Quote Number: ${quote.QuoteNumber || '—'}`);
      doc.moveDown(0.75);

      doc.fontSize(10).font('Helvetica-Bold').fillColor('#111827').text('Account: ', { continued: true }).font('Helvetica').text(quote.Opportunity?.Account?.Name || '—');
      doc.font('Helvetica-Bold').text('Opportunity: ', { continued: true }).font('Helvetica').text(quote.Opportunity?.Name || '—');
      doc.font('Helvetica-Bold').text('Status: ', { continued: true }).font('Helvetica').text(quote.Status || '—');
      doc.font('Helvetica-Bold').text('Expiration Date: ', { continued: true }).font('Helvetica').text(quote.ExpirationDate ? new Date(quote.ExpirationDate).toLocaleDateString() : 'No expiration set');
      doc.font('Helvetica-Bold').text('Prepared By: ', { continued: true }).font('Helvetica').text(user?.name || '—');
      doc.moveDown();

      if (quote.Description) {
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#111827').text('Notes');
        doc.fontSize(9).font('Helvetica').fillColor('#374151').text(quote.Description);
        doc.moveDown();
      }

      // Line items table
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#111827').text('Products & Services');
      doc.moveDown(0.25);

      this.addTable(doc, {
        headers: ['Product', 'Qty', 'Unit Price', 'Discount', 'Line Total'],
        rows: lineItems.map((li) => [
          li.Product2?.Name || li.Description || 'Custom line item',
          String(li.Quantity ?? 0),
          money(li.UnitPrice),
          `${li.Discount || 0}%`,
          money(calculateLineTotal({ quantity: li.Quantity, unitPrice: li.UnitPrice, discount: li.Discount })),
        ]),
      });

      if (lineItems.length === 0) {
        doc.fontSize(9).font('Helvetica').fillColor('#9ca3af').text('No line items on this quote yet.');
      }

      doc.moveDown();

      // Totals summary, right-aligned
      const summaryLines = [
        ['Subtotal', money(totals.subtotal)],
        [`Discount (${quote.Discount || 0}%)`, `-${money(totals.discountAmount)}`],
        ['Tax', money(totals.tax)],
        ['Shipping & Handling', money(totals.shippingHandling)],
      ];

      doc.fontSize(10).font('Helvetica');
      summaryLines.forEach(([label, value]) => {
        doc.text(`${label}: ${value}`, { align: 'right' });
      });
      doc.moveDown(0.25);
      doc.fontSize(13).font('Helvetica-Bold').fillColor('#111827').text(`Grand Total: ${money(totals.grandTotal)}`, { align: 'right' });

      doc.moveDown(2);
      doc.fontSize(8).font('Helvetica').fillColor('#9ca3af').text(
        `Generated on ${new Date().toLocaleString()} by ${user?.name || 'Sales Pipeline Intelligence'}. This quotation is valid until the expiration date shown above.`,
        { align: 'center' }
      );

      return doc;
    } catch (error) {
      throw new Error(`Quote PDF export failed: ${error.message}`);
    }
  }

  addTable(doc, table) {
    const { headers, rows } = table;
    const columnWidth = (doc.page.width - 100) / headers.length;
    const rowHeight = 30;

    let y = doc.y;

    // Headers
    doc.fontSize(10).font('Helvetica-Bold');
    headers.forEach((header, i) => {
      doc.text(header, 50 + i * columnWidth, y, {
        width: columnWidth - 10,
      });
    });

    y += rowHeight;
    doc.moveTo(50, y).lineTo(doc.page.width - 50, y).stroke();
    y += 10;

    // Rows
    doc.font('Helvetica');
    rows.forEach((row) => {
      row.forEach((cell, i) => {
        doc.fontSize(9).text(cell, 50 + i * columnWidth, y, {
          width: columnWidth - 10,
        });
      });
      y += rowHeight;

      if (y > doc.page.height - 50) {
        doc.addPage();
        y = 50;
      }
    });
  }
}

export default new ExportService();