
import { Parser } from 'json2csv';
import PDFDocument from 'pdfkit';

class ExportService {
  async exportToCSV(opportunities) {
    try {
      const fields = [
        'name',
        'amount',
        'stage',
        'closeDate',
        'probability',
        'accountId',
      ];

      const parser = new Parser({ fields });
      const csv = parser.parse(opportunities);

      return csv;
    } catch (error) {
      throw new Error(`CSV export failed: ${error.message}`);
    }
  }

  async exportToPDF(opportunities, user) {
    try {
      const doc = new PDFDocument({
        margin: 50,
        bufferPages: true,
      });

      // Add header
      doc.fontSize(20).text('Sales Pipeline Report', { align: 'center' });
      doc.fontSize(12).text(`Generated by: ${user.name}`, { align: 'center' });
      doc.fontSize(10).text(`Date: ${new Date().toLocaleDateString()}`, {
        align: 'center',
      });
      doc.moveDown();

      // Add summary
      const totalValue = opportunities.reduce((sum, opp) => sum + (opp.amount || 0), 0);
      doc.fontSize(12).text('Pipeline Summary');
      doc.fontSize(10);
      doc.text(`Total Opportunities: ${opportunities.length}`);
      doc.text(`Total Pipeline Value: $${totalValue.toLocaleString()}`);
      doc.moveDown();

      // Add table
      const table = {
        title: 'Opportunities',
        headers: ['Opportunity Name', 'Amount', 'Stage', 'Close Date'],
        rows: opportunities.map((opp) => [
          opp.name,
          `$${(opp.amount || 0).toLocaleString()}`,
          opp.stage,
          new Date(opp.closeDate).toLocaleDateString(),
        ]),
      };

      this.addTable(doc, table);

      return doc;
    } catch (error) {
      throw new Error(`PDF export failed: ${error.message}`);
    }
  }

  addTable(doc, table) {
    const { headers, rows } = table;
    const columnWidth = (doc.page.width - 100) / headers.length;
    const rowHeight = 30;

    let y = doc.y;

    // Headers
    doc.fontSize(10).font('Helvetica-Bold');
    headers.forEach((header, i) => {
      doc.text(header, 50 + i * columnWidth, y, {
        width: columnWidth - 10,
      });
    });

    y += rowHeight;
    doc.moveTo(50, y).lineTo(doc.page.width - 50, y).stroke();
    y += 10;

    // Rows
    doc.font('Helvetica');
    rows.forEach((row) => {
      row.forEach((cell, i) => {
        doc.fontSize(9).text(cell, 50 + i * columnWidth, y, {
          width: columnWidth - 10,
        });
      });
      y += rowHeight;

      if (y > doc.page.height - 50) {
        doc.addPage();
        y = 50;
      }
    });
  }
}

export default new ExportService();